### ISSUE TITLE
Mod auth mellon is NOT checking the SAML Response signature

### ISSUE THREAD

**Issue by ThemGit** [latchset/mod_auth_mellon#117]
I am using the mod auth mellon on apache for authentication on my SP.

I have added on my SP metadata the directives (AuthnRequestsSigned="true" WantAssertionsSigned="true")to require signed responses. So my sp.xml has this line

<SPSSODescriptor
   AuthnRequestsSigned="true"
   WantAssertionsSigned="true"
   protocolSupportEnumeration="urn:oasis:names:tc:SAML:2.0:protocol"
>
I run a burpSuite test when receiving the SAML response from the IdP and I see that removing the signature Mellon still accepts the response instead of rejecting (as it should, because I WantAssertionsSigned, right?), so I am still able to login.

The documentation for Mellon is somewhat outdated and other than the readme.doc there are not a lot of resources.

**Does anyone know how I can force Mellon to check the SAML Response signature? **

I made sure that all the SAML Responses had a signature value in their payload. I made sure that the signature value matched the public key value of the IDP.

FYI: Asking ChatGPT gives answers about directives that do not exist in the code. Neither on this one nor on previous versions

![image](https://user-images.githubusercontent.com/8544353/217510896-61102ff3-8e45-46b5-b614-fe5ee39c829f.png)

**Comment by thijskh** [comment]
I'm confused by your report.

Obviously Mellon checks the signatures contained in responses that it receives and this does not need to be 'enabled', because if you don't check these your SAML implementation provides 0 security and anyone can send a valid assertion.

I've just tried and changed the certificate in my IdP metadata and sure enough, I get a bad request HTTP response and the following is logged:
```
[Fri Feb 24 08:59:45.508625 2023] [auth_mellon:error] [pid 55815] [client 2001:610:450:5a::6:60965] Error processing authn response. Lasso error: [-111] Failed to verify signature., SAML Response: StatusCode1="urn:oasis:names:tc:SAML:2.0:status:Success", StatusCode2="(null)", StatusMessage="(null)",
```

Your message does seem to conflate two things though: a SAML 2.0 message can have the entire response signed and/or also the assertion part contained in it. You talk about response signing while you reference `WantAssertionsSigned` which is about signing the Assertion block. Can you clarify: do you want entire responses to be signature validated, or only the assertion part, and/or both? Or rather, what is it that you want to achieve specifically?

I do not know what the sweeping statement "The documentation for Mellon is somewhat outdated" means, as far as I know it's up to date with how Mellon works, where it's not, please provide specifics so we can fix it.

I don't know why I would need information about what ChatGPT does or does not think. It just seems like a bit of nonsense that it returns? I don't think the mentioned setting even exists.

Surely there can be a bug somewhere, or documentation that can be improved, but we'd need to know more specifically what your exact config is, what you expect to happen and what happens instead.

**Comment by ThemGit** [comment]
Hello and thanks a lot for the reply on the issue I am having.

> Can you clarify: do you want entire responses to be signature validated, or only the assertion part, and/or both? Or rather, what is it that you want to achieve specifically?
What I want is to be able to reject a SAML response if it does not have the assertion signed or the whole response signed. Any of the two or even better both of them, would be great.

In the issue I am mentioning above what I believe is signed is the whole response (not the assertion) and that this signature is removed. I am attaching to this response the SAMLResponse XML that includes the signature and the one where the signature is removed. The one where the signature is removed is still accepted by Mellon and the user is able to login.

[withSigAnon.txt](https://github.com/latchset/mod_auth_mellon/files/10838548/withSigAnon.txt)
[withoutSigAnon.txt](https://github.com/latchset/mod_auth_mellon/files/10838549/withoutSigAnon.txt)

I only mentioned chatGPT because of the nonsense that is mentioned there only as a comment so that it is know that actually there are useless non-existent directives being mentioned there.

Thanks again for your help on this.

**Comment by thijskh** [comment]
Mellon uses the Lasso library to process SAML messages. Lasso has the default logic that:
- If a response signature is present it must be valid
- If a response signature is not present, and an assertion signature is present and valid, accept the message

This is in line with what several other SAML implementations do as the WebSSO profile allows for Responses to be unsigned. At least Shibboleth, SimpleSAMLphp and Satosa will work similarly.

Lasso itself can be asked to require a signed response but as far as I'm aware Mellon does not currently expose a configuration option to have it ask this of lasso (need to pass `LASSO_PROFILE_SIGNATURE_VERIFY_HINT_FORCE` to signature validation). If you really require this functionality you could provide a PR to do it. (The metadata is not the place to configure Mellon's behaviour, just an expression of its configuration.)

However you have still not answered my original question and that is what problem you are trying to solve: "what is it that you want to achieve specifically?" Checking the response signature is a solution, but to what problem? I'm asking because as far as I'm aware Mellon only exposes elements from the Assertion to the application. So I'm really curious what you want to use from the Response that is not in the Assertion and therefore requires the Response to be signed and validated.

**Comment by ThemGit** [comment]
What I am trying to solve is to ensure that:

- if a response has a signed assertion --> is accepted
- if a response is signed altogether --> is accepted
- if no assertion or response signature is present --> reject the response

In the example response attached on the "WithoutSigAnon.txt" you can see that when removing the Signature of the IDP the response still gets accepted.

Doesn't this fall in the problem category of your first answer ?

> ...because if you don't check these your SAML implementation provides 0 security and anyone can send a valid assertion

**Comment by ThemGit** [comment]
> Checking the response signature is a solution, but to what problem? I'm asking because as far as I'm aware Mellon only exposes elements from the Assertion to the application. So I'm really curious what you want to use from the Response that is not in the Assertion and therefore requires the Response to be signed and validated.

Basically I am trying to make sure that the response is really coming from the IDP and that the content is what the IDP wanted to send.

Not checking the signature opens up the window for possible attacks as we can't know if the response if really coming from the IDP or it's content could be edited along the way and used for an unauthorized privilege elevation.

Unless Mellon is using some other way to protect against the above, as far as I know, the signature is the only way to address this risk.

**Comment by thijskh** [comment]
I'm afraid I cannot reproduce it. If I create an assertion without any signature element, I get:

```
[Mon Feb 27 14:18:39.031533 2023] [auth_mellon:error] [pid 19297] [client 2001:610:450:5a::6:56897] Error processing authn response. Lasso error: [101] Signature element not found., SAML Response: StatusCode1="urn:oasis:names:tc:SAML:2.0:status:Success", StatusCode2="(null)", StatusMessage="(null)"
```

I guess exactly what is expected. I tried the assertion you give but it's mangled and does not even seem to survive parsing by Mellon, let alone have the signature check pass.

**Comment by thijskh** [comment]
Just a theory here: is it possible that the encrypted assertion you give contains a validly signed assertion within the encrypted part?

**Comment by ThemGit** [comment]
Steps to re-produce

1.	Download burpsuite community edition (using v2022.12.27)
2.	Install the SAML Raider extension by clicking on the extensions tab  BApp Store  Search SAML Raider   scroll down to install
3.	After the addon installation click on the Proxy tab
4.	Select the Intercept tab
5.	Click on Open browser
6.	On the Chromium window type in the SP url
7.	GO back to the Burpsuite and click on Intercept On. From this point on every request on the chromium window will need to be “approved” by Burpsuite. The “approve” command is the “Forward” button.
8.	On the Chromium window trigger the SAML login, on the Burp window monitor the sequence of GET/POST requests and click on the Forward button
9.	When the SAML Response post request step is received do NOT click on Forward, click on SAML Raider  (it will show up right next to the "Raw" and "Hex" tabs, when SAML content is identified)                                                      
10.	There click on “Remove Signatures”  
11.	Now click on Forward
12.	The Response is accepted by Mellon (unfortunately )

**Comment by thijskh** [comment]
Thanks for the detailed steps. I've confirmed the following for myself:

1. Using burpsuite to "remove signatures" from a message with an unencrypted assertion results in Bad request at mellon with logging "[101] Signature element not found"
2. Using burpsuite to "remove signatures" from a message with an encrypted assertion without an inner signature results in Bad request at mellon with logging "[101] Signature element not found."
3. Using burpsuite to "remove signatures" from an encrypted assertion with an inner signature inside the encrypted assertion results in a valid login
4. Comparing before and after XMLs from burpsuite when using the "remove signatures" button for the latter case shows that the encrypted data is unchanged (i.e.: saml raider does not decrypt assertion, remove inner signature, reencrypt assertion - rather keeps it completely unchanged).

All in all this seems like correct behaviour to me and I think it's likely that your test setup has a signature on the assertion inside the assertion encryption which is passed to mellon unmodified and then correctly accepted by mellon. Can you confirm this?

**Comment by ThemGit** [comment]
Hello again,

do you have an easy way to be able to decrypt the encryptedAssertion element?

I am looking into the mellonDiagnostics for the flow where I remove the signatures through Burpsuite and see that I get a log showing first a <saml2:Assertion> and then a <saml:EncryptedAssertion>

Is it correct to assume that the mellonDiagnostics logs show the decrypted saml assertion and then the encrypted version of them received?

I am attaching a sanitized version  of the log entry so that you can see also for yourself.
[MellonDiagnosticsEntry.txt](https://github.com/latchset/mod_auth_mellon/files/10861901/MellonDiagnosticsEntry.txt)

**Comment by thijskh** [comment]
Indeed when mellon logs this after `SAML Response (am_handle_post_reply):` it means it has decrypted any encrypted assertions. As you can see the decrypted assertion has an embedded signature in it.

**Comment by ThemGit** [comment]
@thijskh  Thank you for the help and responses! this has been very useful.

I am happy this stays here as I hope it will serve as information for more people who might want to find our more information regarding the signature validation and it's configuration in the future.

Cheers!
