### ISSUE TITLE
SP initiated SAML login via the HTTP-POST binding does not work with SameSite != None

### ISSUE THREAD

**Issue by rpluem** [latchset/mod_auth_mellon#20]
SP initiated SAML login via the HTTP-POST binding does not work for me if `MellonCookieSameSite`
is set to anything but None.
The reason for this is that the browser does not sent the cookie defined in `MellonVariable`
when the IDP responds back with the autosubmitform that is sent to the postresponse handler.
IMHO the browser behaves correctly here with SameSite set to lax or strict for the cookie.

The question I ask myself now is why that cookie needs to be present with the POST request.
Inspecting the code the cookie only contains the static string "cookietest" and nothing but its
presence is checked. This whole mechanism was introduced in 18a8e091a690e942cdc9dc12fb22502052b00998
via line `3265` in `am_send_login_authn_request`: 

```C
am_cookie_set(r, "cookietest");
```

and the check for the cookie to be present in the non paos case via line `1994` in `am_handle_reply_common`:

```C
if(am_cookie_get(r) == NULL) {
```

What is the purpose of this check? Does it somehow increase security? If not I would propose to either

- Remove setting that cookie and the check or
- In case MellonCookieSameSite is set to anything but none do not fail if the cookie is not present.

I could create a PR for both approaches once the way forward is agreed.

**Comment by thijskh** [comment]
The code is originally added to provide early and more meaningful feedback to the user (your cookies do not work) instead of plainly failing on a missing mellon-cookie later on in the process. A special 'cookie error page' can then be shown. This is described a bit more elaborately in the manual:
https://github.com/latchset/mod_auth_mellon/blob/master/doc/user_guide/mellon_user_guide.adoc#mellon_cookie

So mellon does require cookies to work. I think as I understand it, it may indeed be the case that if the cookietest is removed, mellon would work with other SameSite values. That would obviously be a win.

The problem is to devise a way to handle people who do indeed block/browsers that lose the mellon-cookie cookie. Must avoid something like a redirect loop and it must be handled gracefully. Any ideas on how to do that without the cookietest?

**Comment by rpluem** [comment]
Thanks for providing more insight in the motivation and the background. Sorry for missing the above document before asking. While thinking of a possible solution I became aware of another scenario where this could fail like for me: If as announced by some browser vendors their browsers will default to SameSite lax in case it is not set in the cookie these could fail as well even without setting `MellonCookieSameSite`.
My idea now is to ensure that the cookie with this "test value" (so the one that is set in line `3265` in `am_send_login_authn_request` is sent with SameSite None, provided that the SameSite setting is not suppressed   by a set `MELLON_DISABLE_SAMESITE`  environment variable.
I guess using SameSite None would be a fair tradeoff to keep the "test the cookies are enabled" funktionality while not lowering security as the cookie only contains the static value. On the other hand there might be people who dislike this and would rather drop the "test the cookies are enabled" functionality. For these we could add a directive that just disables the "test the cookies are enabled" functionality. What do you think?

**Comment by thijskh** [comment]
Yes, the implementation of SameSite=Lax will definititely affect many SAML deployments because it prohibits sending any cookies in the cross-site POST that is part of the SAML websso HTTP-POST binding. So not only mellon, but also any application specific session or settings cookies will be missing. It might therefore be needed in any case to set SameSite=None for websites that want to receive HTTP-POST SAML binding messages.

I still agree that in the ideal world the cookietest cookie is not needed and it would surely make things more robust. I'm most worried about things like redirect loops. If we can find another way to prevent that, that would be great.

So do I interpret you correctly that basically you'd want to split up the SAMESITE setting to not apply to all mellon's cookies, but apply a different SameSite attribute (None) to the cookietest than to the mellon-cookie cookie?

**Comment by rpluem** [comment]
Basically yes. If the SameSite stuff should be set (so `MellonCookieSameSite` configured and `MELLON_DISABLE_SAMESITE` not set for this particular request) I would always set SameSite to None for this testing content and later on when the cookie contains the session id behave the same way as  currently (so apply `MellonCookieSameSite` if set and `MELLON_DISABLE_SAMESITE` unset).
In addition I could think of a directive that just disables the cookie test e.g. `MellonDisableCookieTest` for people who are sure that their clients browsers have cookies enabled but don't like the SameSite None to be set on the cookie for the test content. Currently I have no idea how to avoid redirect loops in case `MellonDisableCookieTest` would be on, but have an appropriate warning in the documentation that this can happen and have it default to off.

**Comment by rpluem** [comment]
Does the outlined approach look acceptable?

**Comment by thijskh** [comment]
Yes, in principle sounds good. Not sure though what value the `MellonDisableCookieTest` setting would add though. The "cost" of the cookietest cookie is not really so significant that it would make sense to provide infrastructure to disable it.

I would still have some hope for an even better solution where we remove the cookietest and still be able to catch errors effectively. That would be the cleanest solution, but I admit I have not worked it out in detail yet. So your approach might in any case be a good improvement over what we have.

**Comment by rpluem** [comment]
Thanks for the feedback. I will try to work out a PR for further discussion. The idea of `MellonDisableCookieTest` is to provide an option for those people who would rather die than seeing a cookie with SameSite set to None being emitted :-). But I will park this idea until these people pop up and create the PR without this.

**Comment by thijskh** [comment]
That seems unlikely since many SAML 2.0 HTTP-POST implemenations will be sending it so it should not be extraordinary.

**Comment by rpluem** [comment]
Created PR #23

**Comment by rpluem** [comment]
Any comment on the PR?

**Comment by simo5** [comment]
Looks reasonable to me, but I would like someone else with more fresh knowledge of this aspect of mellon to comment on the PR

**Comment by rpluem** [comment]
Any further comments?

**Comment by thijskh** [comment]
I have seen your PR but not yet had the time to review it

**Comment by rpluem** [comment]
Thanks for the update

**Comment by rpluem** [comment]
Thanks for merging.
