### ISSUE TITLE
Mellon incorrect user - not related to this fork

### ISSUE THREAD

**Issue by mkanugan** [latchset/mod_auth_mellon#34]
We have a config 

_MellonCacheSize 6000
MellonLockFile "/run/mod_auth_mellon/lock"_

but we have not given permission for the apache user to write to run directory.

Can we know what would happen in that case, how is the session managed and where is it stored.

We are having issues when some users are getting other user's old session but only happens sometimes not always. our Mellon config as follows

_MellonEnable "auth"
Require valid-user
AuthType "Mellon"
MellonVariable "cookie"
MellonSamlResponseDump Off
MellonSecureCookie On
MellonSessionDump Off
MellonSessionLength 1800_

How do i debug as diagnostics is not built in to this Mellon.

Getting 200 status code instead of 303 redirect with some other user attached and starts to serve the protected content.  httpd version is 2.4.6 also have **Header always set X-Frame-Options DENY** in httpd config

Can you please enlighten us where we are going wrong?

Upon closer look seems that session is being highjacked based on mellon-cookie, is there any way to stop this. So authentication is not done and hence gives other persons details.

Is there any possibility of mellon-cookie being reassigned to other user, say after 1 day etc, the derivation of cookie id does it depend on date etc so that it varies

**Comment by thijskh** [comment]
The session ID in the mellon cookie is generated by OpenSSL's `RAND_bytes`. So that should never result in duplicate IDs, also not over time. If different people arrive with the same mellon session ID, then they are "logged in" and indeed will get the content associated with that session. I think you need to debug in your environment why two people would end up with the same session ID. Perhaps there's some kind of 'cache' or '(reverse) proxy' in between that does not properly distinguish different users?

You say Mellon is not built with diagnostics. Of course one choice is to build it with diagnostics. But you can also/additionally set Apache's log level to 'debug'. This will also give more logging from mod_mellon. And you can log specifics of the request, e.g. the cookies sent, by adding some Apache logging configuration. But that is all more related to Apache config than to this specific module.

**Comment by mkanugan** [comment]
Thanks for taking time to reply, much helpful. After more log analysis, we see that the first request from the user getting corrupted and redirected to idp as expected, so the mellon session id is coming along with the request somehow, that user has got a correct session 1 day back or some days back. We have now put logger to log in cookies, so we will know exactly what is happening. Is there any way to check more on session id, also can we know where Mellon stores its session information as we cannot see the lock file and also no permission for apache user to the run location.

**Comment by thijskh** [comment]
They are stored in Apache's shared memory (shm).

**Comment by mkanugan** [comment]
thanks for the help. We will monitor and see what is the real issue.
