### ISSUE TITLE
Migrated to Latchset and now IDP SAML fails

### ISSUE THREAD

**Issue by jdmevo123** [latchset/mod_auth_mellon#87]
I have migrated to the latest version, however now my SAML authentication fails. Is there anything specific I need to change to ensure I can get up and running.

From what I can tell from the logs, my IDP is responding with SAML Request signature validation failed: Error during signature verification

Any ideas?

**Comment by thijskh** [comment]
The error indicates that, well, your IdP cannot verify the signature on your SAML authentication request. This request is signed with the certificate you configured in Mellon. Maybe you changed the certificate but did not send the new metadata to the IdP so they can import it? Probably there's a mismatch there between your certificate and what the IdP knows of you.

**Comment by jdmevo123** [comment]
@thijskh Thanks, that is what I would of assumed, however the exact configuration works on the older code base, I have checked the md5 of the certificates on both servers and they all match. The configuration on both machines is the same as well.

**Comment by thijskh** [comment]
From what version of mod_mellon did you upgrade to which version?

**Comment by jdmevo123** [comment]
from the Uninett/mod_auth_mellon V 0.14.2 to this repo V0.18

**Comment by thijskh** [comment]
The only change I think might explain it is that mellon_create_metadata script will now set AuthnRequestSigned to true in the generated metadata. If you indeed also regenerated the metadata with this script after the upgrade, it could be that your IdP did not validate signatures before and does now based on the new metadata. It is not a full explanation because you report that the configured certificates are in fact identical on both sides. But I have nothing more to offer here. You could investigate whether the IdP indeed now verifies authnrequest signatures and what happens if you turn them off (which is not really a risk in itself), to at least pinpoint this as the thing that changed.

**Comment by jdmevo123** [comment]
mmm yes both have the AuthnRequestSigned set to true, 
  <SPSSODescriptor AuthnRequestsSigned="true" WantAssertionsSigned="false" protocolSupportEnumeration="urn:oasis:names:tc:SAML:2.0:protocol">
    <KeyDescriptor use="signing">

**Comment by thijskh** [comment]
I trust you can now debug the issue further with your idp?

**Comment by jdmevo123** [comment]
They can only tell me the Error during signature verification error. So it appears to be on the mod auth mellon side. 

What im going to do is rebuild and reconfigure off the latest and see if it was a corrupt installation.

**Comment by thijskh** [comment]
I don't believe Mellon's signatures are incorrect since it is in wide use without issue. I would bet there is a discrepancy between expected certificate and actual certificate, or between used hashing versions (mellon uses sha2, idp expects sha1?) or otherwise a configuration mismatch between the sides. In my experience that is a vast more likely explanation than a build error.

**Comment by jdmevo123** [comment]
It may be an issue with Lasso, where can I get the latest, as I cannot find it installed

Is it just the python-lasso framework?

**Comment by thijskh** [comment]
https://lasso.entrouvert.org/

**Comment by jdmevo123** [comment]
Thanks, Im getting somewhere, no I can see the following in my logs:

`SSL input filter read failed.
[Mon Dec 13 12:21:47.283947 2021] [ssl:info] [pid 31195] [client 121.216.164.108:50336] AH02008: SSL library error 1 in handshake (server <server_name>:443)
[Mon Dec 13 12:21:47.284080 2021] [ssl:info] [pid 31195] SSL Library Error: error:14094416:SSL routines:ssl3_read_bytes:sslv3 alert certificate unknown (SSL alert number 46)
[Mon Dec 13 12:21:47.284147 2021] [ssl:info] [pid 31195] [client 121.216.164.108:50336] AH01998: Connection closed to child 2 with abortive shutdown (server <server_name>:443)
[Mon Dec 13 12:21:48.818516 2021] [ssl:info] [pid 31197] [client 23.55.56.232:51193] AH01964: Connection to child 4 established (server <server_name>:443)
[Mon Dec 13 12:21:48.818945 2021] [ssl:debug] [pid 31197] ssl_engine_io.c(1228): (70014)End of file found: [client 23.55.56.232:51193] AH02007: SSL handshake interrupted by system [Hint: Stop button pressed in browser?!]
[Mon Dec 13 12:21:48.819047 2021] [ssl:info] [pid 31197] [client 23.55.56.232:51193] AH01998: Connection closed to child 4 with abortive shutdown (server <server_name>:443)`

**Comment by jdmevo123** [comment]
Ive triple checked all the certificates and the IDP certificate. Have you ever encountered this issue?

**Comment by jdmevo123** [comment]
Issue resolved, rebuilt and the issue no longer is present.
